# -*- mode: ruby -*-
# vi: set ft=ruby :

name = "3shake"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.define "master" do |cf|
    cf.vm.hostname = name + "-k8s-master"
    cf.vm.network :public_network, :bridge => "Realtek PCIe 2.5GbE Family Controller", ip: "192.168.50.60"
    cf.vm.provider "virtualbox" do |vb|
      vb.name   = cf.vm.hostname
      vb.cpus   = 2
      vb.memory = 4096
    end
  end

  config.vm.define "node-001" do |cf|
    cf.vm.hostname = name + "-k8s-node-001"
    cf.vm.network :public_network, :bridge => "Realtek PCIe 2.5GbE Family Controller", ip: "192.168.50.61"
    cf.vm.provider "virtualbox" do |vb|
      vb.name   = cf.vm.hostname
      vb.cpus   = 2
      vb.memory = 4096
    end
  end

  config.vm.define "node-002" do |cf|
    cf.vm.hostname = name + "-k8s-node-002"
    cf.vm.network :public_network, :bridge => "Realtek PCIe 2.5GbE Family Controller", ip: "192.168.50.62"
    cf.vm.provider "virtualbox" do |vb|
      vb.name   = cf.vm.hostname
      vb.cpus   = 2
      vb.memory = 4096
    end
  end

  config.vm.define "node-003" do |cf|
    cf.vm.hostname = name + "-k8s-node-003"
    cf.vm.network :public_network, :bridge => "Realtek PCIe 2.5GbE Family Controller", ip: "192.168.50.63"
    cf.vm.provider "virtualbox" do |vb|
      vb.name   = cf.vm.hostname
      vb.cpus   = 2
      vb.memory = 4096
    end
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "server.yml"
  end

end
